### PR TITLE
Possible corrections for Array encoding

### PR DESCRIPTION
**Pull request by wckivX**
Here are the possible changes for review.  Thanks

### CODE REVIEW

**Comment by nauful** [comment]
Will test this locally. I disagree with changing UInt32 to Int32 because it's possible to have values >0x7FFFFFu without equaling 0xFFFFFFu/-1, so I will merge these changes into another commit.

**Comment by wckivX** [comment]
From:
https://reference.opcfoundation.org/v105/Core/docs/Part3/5.6.2/

Under ArrayDimensions

Regardless of the number of dimensions, the maximum number of elements of an array transferred on the wire is 2147483647 (max Int32).

So, under OPC UA, it seems even multi-dimensional arrays are limited to 0x7FFFFFFF total elements.

If you disagree, you still should fix the code in Net Core\LibUA\Client.ss, CreateMonitered Items, Line 4044.  It reads the number of elements as UInt32 and attempts to decode that many elements from the response.  It does not actually create an array with that length.  This is where the FactoryTalk Linux Gateway server's response caused errors in my OPC UA client.

I

**Comment by nauful** [comment]
Take a look at this and let me know if that resolves the issue: https://github.com/nauful/LibUA/compare/master...nauful/fix-missing-array-size

**Comment by wckivX** [comment]
Yes, that should resolve it.
Thanks.

[OPC UA Online Reference](https://reference.opcfoundation.org/)
V105
Part 6 5.1.9

Decoders shall be able to handle all variations supported by the DataEncoding, however, decoders are not required to preserve the distinction. When testing for equality, applications shall treat null and empty arrays as equal.

Part 6 5.2.5 Arrays changed between V104 and V105 (current), no longer requiring preservation of null vs length 0 arrays.

**Comment by nauful** [comment]
It's not necessary to preserve null vs empty arrays but it simplifies usage and reduces crashes due to nulls.

**Pull request closed without merging**
